### PR TITLE
added conn_mt:Query, conn_mt:QueryRow, conn_mt:QueryValue

### PR DESCRIPTION
**Pull request by Be1zebub**
Convenience!

### CODE REVIEW

**Comment by Be1zebub** [comment]
Usage examples:
```lua
function User:FetchExp()
    return db:QueryValue("SELECT `exp` FROM `leveling` WHERE `id` = ?;", self.id, "exp") or 0
end

function User:SaveExp()
    db:Query("REPLACE INTO `leveling` (`id`, `exp`) VALUES(?, ?);", {self.id, self.exp})
end

local leaders = db:Query("SELECT * FROM `leveling` ORDER BY `exp` DESC LIMIT 10 OFFSET ?;", offset)
for i, user in ipairs(leaders) do
	print(client:getUser(user.id).name, user.exp)
end

local leader = db:QueryRow("SELECT * FROM `leveling` ORDER BY `exp` DESC;") -- returns the first row found
```

**Comment by SinisterRectus** [comment]
Can you write more about what this is and why it's needed?

**Comment by Be1zebub** [comment]
These are just functions that make queries convenient, i added a usage example above.

**Comment by SinisterRectus** [comment]
I don't think it's appropriate to start adding, maintaining, and documenting new API features. This is really just meant to be a lit mirror of the SciLua package.

**Pull request closed without merging**
